import json

with open('data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

new_cells = [
    {
        "cell_type": "code",
        "id": "model_1_logistic_regression",
        "metadata": {},
        "source": [
            "from sklearn.linear_model import LogisticRegression\n",
            "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report\n",
            "import pickle\n",
            "\n",
            "print('MODEL 1: LOGISTIC REGRESSION')\n",
            "print('-' * 40)\n",
            "\n",
            "lr_model = LogisticRegression(C=0.8, max_iter=1000, solver='lbfgs', random_state=42)\n",
            "lr_model.fit(X_train, y_train)\n",
            "\n",
            "y_pred_lr = lr_model.predict(X_test)\n",
            "y_proba_lr = lr_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "train_acc_lr = accuracy_score(y_train, lr_model.predict(X_train))\n",
            "test_acc_lr = accuracy_score(y_test, y_pred_lr)\n",
            "precision_lr = precision_score(y_test, y_pred_lr, zero_division=0)\n",
            "recall_lr = recall_score(y_test, y_pred_lr, zero_division=0)\n",
            "f1_lr = f1_score(y_test, y_pred_lr, zero_division=0)\n",
            "auc_lr = roc_auc_score(y_test, y_proba_lr)\n",
            "\n",
            "print(f'Train Acc: {train_acc_lr:.4f} | Test Acc: {test_acc_lr:.4f}')\n",
            "print(f'Precision: {precision_lr:.4f} | Recall: {recall_lr:.4f} | F1: {f1_lr:.4f}')\n",
            "print(f'\\nConfusion Matrix:')\n",
            "print(confusion_matrix(y_test, y_pred_lr))\n",
            "print(f'\\nClassification Report:')\n",
            "print(classification_report(y_test, y_pred_lr))\n",
            "\n",
            "with open('logistic_regression_model.pkl', 'wb') as f:\n",
            "    pickle.dump(lr_model, f)"]
    },
    {
        "cell_type": "code",
        "id": "model_2_random_forest",
        "metadata": {},
        "source": [
            "from sklearn.ensemble import RandomForestClassifier\n",
            "\n",
            "print('MODEL 2: RANDOM FOREST')\n",
            "print('-' * 40)\n",
            "\n",
            "rf_model = RandomForestClassifier(n_estimators=200, max_depth=12, min_samples_split=3,\n",
            "                                  min_samples_leaf=2, random_state=42, n_jobs=-1)\n",
            "rf_model.fit(X_train, y_train)\n",
            "\n",
            "y_pred_rf = rf_model.predict(X_test)\n",
            "y_proba_rf = rf_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "train_acc_rf = accuracy_score(y_train, rf_model.predict(X_train))\n",
            "test_acc_rf = accuracy_score(y_test, y_pred_rf)\n",
            "precision_rf = precision_score(y_test, y_pred_rf, zero_division=0)\n",
            "recall_rf = recall_score(y_test, y_pred_rf, zero_division=0)\n",
            "f1_rf = f1_score(y_test, y_pred_rf, zero_division=0)\n",
            "auc_rf = roc_auc_score(y_test, y_proba_rf)\n",
            "\n",
            "print(f'Train Acc: {train_acc_rf:.4f} | Test Acc: {test_acc_rf:.4f}')\n",
            "print(f'Precision: {precision_rf:.4f} | Recall: {recall_rf:.4f} | F1: {f1_rf:.4f}')\n",
            "print(f'\\nConfusion Matrix:')\n",
            "print(confusion_matrix(y_test, y_pred_rf))\n",
            "print(f'\\nClassification Report:')\n",
            "print(classification_report(y_test, y_pred_rf))\n",
            "\n",
            "# feature importance\n",
            "feat_imp = pd.DataFrame({'Feature': feature_cols, 'Importance': rf_model.feature_importances_})\n",
            "print(feat_imp.sort_values('Importance', ascending=False))\n",
            "\n",
            "with open('random_forest_model.pkl', 'wb') as f:\n",
            "    pickle.dump(rf_model, f)"]
    },
    {
        "cell_type": "code",
        "id": "model_3_gradient_boosting",
        "metadata": {},
        "source": [
            "from sklearn.ensemble import GradientBoostingClassifier\n",
            "\n",
            "print('MODEL 3: GRADIENT BOOSTING')\n",
            "print('-' * 40)\n",
            "\n",
            "gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.12, max_depth=4,\n",
            "                                      subsample=0.85, random_state=42)\n",
            "gb_model.fit(X_train, y_train)\n",
            "\n",
            "y_pred_gb = gb_model.predict(X_test)\n",
            "y_proba_gb = gb_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "train_acc_gb = accuracy_score(y_train, gb_model.predict(X_train))\n",
            "test_acc_gb = accuracy_score(y_test, y_pred_gb)\n",
            "precision_gb = precision_score(y_test, y_pred_gb, zero_division=0)\n",
            "recall_gb = recall_score(y_test, y_pred_gb, zero_division=0)\n",
            "f1_gb = f1_score(y_test, y_pred_gb, zero_division=0)\n",
            "auc_gb = roc_auc_score(y_test, y_proba_gb)\n",
            "\n",
            "print(f'Train Acc: {train_acc_gb:.4f} | Test Acc: {test_acc_gb:.4f}')\n",
            "print(f'Precision: {precision_gb:.4f} | Recall: {recall_gb:.4f} | F1: {f1_gb:.4f}')\n",
            "print(f'\\nConfusion Matrix:')\n",
            "print(confusion_matrix(y_test, y_pred_gb))\n",
            "\n",
            "with open('gradient_boosting_model.pkl', 'wb') as f:\n",
            "    pickle.dump(gb_model, f)"]
    },
    {
        "cell_type": "code",
        "id": "model_4_svm",
        "metadata": {},
        "source": [
            "from sklearn.svm import SVC\n",
            "\n",
            "print('MODEL 4: SVM (RBF)')\n",
            "print('-' * 40)\n",
            "\n",
            "svm_model = SVC(kernel='rbf', C=4.0, gamma='scale', probability=True, random_state=42)\n",
            "svm_model.fit(X_train, y_train)\n",
            "\n",
            "y_pred_svm = svm_model.predict(X_test)\n",
            "y_proba_svm = svm_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "train_acc_svm = accuracy_score(y_train, svm_model.predict(X_train))\n",
            "test_acc_svm = accuracy_score(y_test, y_pred_svm)\n",
            "precision_svm = precision_score(y_test, y_pred_svm, zero_division=0)\n",
            "recall_svm = recall_score(y_test, y_pred_svm, zero_division=0)\n",
            "f1_svm = f1_score(y_test, y_pred_svm, zero_division=0)\n",
            "auc_svm = roc_auc_score(y_test, y_proba_svm)\n",
            "\n",
            "print(f'Train Acc: {train_acc_svm:.4f} | Test Acc: {test_acc_svm:.4f}')\n",
            "print(f'Precision: {precision_svm:.4f} | Recall: {recall_svm:.4f} | F1: {f1_svm:.4f}')\n",
            "print(f'\\nConfusion Matrix:')\n",
            "print(confusion_matrix(y_test, y_pred_svm))\n",
            "\n",
            "with open('svm_model.pkl', 'wb') as f:\n",
            "    pickle.dump(svm_model, f)"]
    },
    {
        "cell_type": "code",
        "id": "model_5_knn",
        "metadata": {},
        "source": [
            "from sklearn.neighbors import KNeighborsClassifier\n",
            "\n",
            "print('MODEL 5: KNN')\n",
            "print('-' * 40)\n",
            "\n",
            "knn_model = KNeighborsClassifier(n_neighbors=7, weights='distance', metric='minkowski', n_jobs=-1)\n",
            "knn_model.fit(X_train, y_train)\n",
            "\n",
            "y_pred_knn = knn_model.predict(X_test)\n",
            "y_proba_knn = knn_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "train_acc_knn = accuracy_score(y_train, knn_model.predict(X_train))\n",
            "test_acc_knn = accuracy_score(y_test, y_pred_knn)\n",
            "precision_knn = precision_score(y_test, y_pred_knn, zero_division=0)\n",
            "recall_knn = recall_score(y_test, y_pred_knn, zero_division=0)\n",
            "f1_knn = f1_score(y_test, y_pred_knn, zero_division=0)\n",
            "auc_knn = roc_auc_score(y_test, y_proba_knn)\n",
            "\n",
            "print(f'Train Acc: {train_acc_knn:.4f} | Test Acc: {test_acc_knn:.4f}')\n",
            "print(f'Precision: {precision_knn:.4f} | Recall: {recall_knn:.4f} | F1: {f1_knn:.4f}')\n",
            "print(f'\\nConfusion Matrix:')\n",
            "print(confusion_matrix(y_test, y_pred_knn))\n",
            "\n",
            "with open('knn_model.pkl', 'wb') as f:\n",
            "    pickle.dump(knn_model, f)"]
    },
    {
        "cell_type": "markdown",
        "id": "model_comparison",
        "metadata": {},
        "source": ["## M. Model Evaluation & Comparison"]
    },
    {
        "cell_type": "code",
        "id": "compare_models",
        "metadata": {},
        "source": [
            "# compare all models\n",
            "results = {\n",
            "    'Model': ['Logistic Regression', 'Random Forest', 'Gradient Boosting', 'SVM', 'KNN'],\n",
            "    'Train Accuracy': [train_acc_lr, train_acc_rf, train_acc_gb, train_acc_svm, train_acc_knn],\n",
            "    'Test Accuracy': [test_acc_lr, test_acc_rf, test_acc_gb, test_acc_svm, test_acc_knn],\n",
            "    'Precision': [precision_lr, precision_rf, precision_gb, precision_svm, precision_knn],\n",
            "    'Recall': [recall_lr, recall_rf, recall_gb, recall_svm, recall_knn],\n",
            "    'F1-Score': [f1_lr, f1_rf, f1_gb, f1_svm, f1_knn],\n",
            "    'ROC-AUC': [auc_lr, auc_rf, auc_gb, auc_svm, auc_knn]\n",
            "}\n",
            "\n",
            "results_df = pd.DataFrame(results).round(4)\n",
            "print(results_df.to_string(index=False))\n",
            "\n",
            "best_idx = results_df['Test Accuracy'].idxmax()\n",
            "best_model_name = results_df.loc[best_idx, 'Model']\n",
            "best_accuracy = results_df.loc[best_idx, 'Test Accuracy']\n",
            "print(f'\\nBest model: {best_model_name} ({best_accuracy*100:.2f}%)')\n",
            "\n",
            "# comparison plot\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "axes[0].barh(results_df['Model'], results_df['Test Accuracy'], color='steelblue')\n",
            "axes[0].axvline(x=0.90, color='red', linestyle='--', label='90% Target')\n",
            "axes[0].set_xlabel('Test Accuracy')\n",
            "axes[0].set_title('Model Accuracy Comparison')\n",
            "axes[0].legend()\n",
            "axes[0].set_xlim([0.7, 1.0])\n",
            "\n",
            "x = np.arange(len(results_df))\n",
            "w = 0.25\n",
            "axes[1].bar(x - w, results_df['Precision'], w, label='Precision')\n",
            "axes[1].bar(x, results_df['Recall'], w, label='Recall')\n",
            "axes[1].bar(x + w, results_df['F1-Score'], w, label='F1')\n",
            "axes[1].set_xticks(x)\n",
            "axes[1].set_xticklabels(results_df['Model'], rotation=45, ha='right')\n",
            "axes[1].legend()\n",
            "axes[1].set_title('Precision / Recall / F1')\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "results_df.to_csv('model_comparison_results.csv', index=False)"]
    },
    {
        "cell_type": "code",
        "id": "save_best_model",
        "metadata": {},
        "source": [
            "# save best model and metadata\n",
            "models_dict = {\n",
            "    'Logistic Regression': lr_model,\n",
            "    'Random Forest': rf_model,\n",
            "    'Gradient Boosting': gb_model,\n",
            "    'SVM': svm_model,\n",
            "    'KNN': knn_model,\n",
            "}\n",
            "\n",
            "best_model = models_dict[best_model_name]\n",
            "with open('best_model.pkl', 'wb') as f:\n",
            "    pickle.dump(best_model, f)\n",
            "print(f'Best model ({best_model_name}) saved to best_model.pkl')\n",
            "\n",
            "with open('feature_names.pkl', 'wb') as f:\n",
            "    pickle.dump(feature_cols, f)\n",
            "\n",
            "import json\n",
            "model_info = {\n",
            "    'best_model_name': best_model_name,\n",
            "    'best_test_accuracy': float(best_accuracy),\n",
            "    'feature_cols': feature_cols,\n",
            "    'all_models': {\n",
            "        'logistic_regression': 'logistic_regression_model.pkl',\n",
            "        'random_forest': 'random_forest_model.pkl',\n",
            "        'gradient_boosting': 'gradient_boosting_model.pkl',\n",
            "        'svm': 'svm_model.pkl',\n",
            "        'knn': 'knn_model.pkl'\n",
            "    }\n",
            "}\n",
            "with open('model_info.json', 'w') as f:\n",
            "    json.dump(model_info, f, indent=2)\n",
            "\n",
            "print('All files saved. Done.')"]
    }
]

for cell in new_cells:
    nb['cells'].append(cell)

with open('data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print(f"Added {len(new_cells)} cells for model training and evaluation")
print(f"Total cells: {len(nb['cells'])}")
