import json

with open('data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Model training and evaluation cells
new_cells = [
    {
        "cell_type": "code",
        "id": "model_1_logistic_regression",
        "metadata": {},
        "source": [
            "from sklearn.linear_model import LogisticRegression\n",
            "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report\n",
            "import pickle\n",
            "\n",
            "print('=' * 80)\n",
            "print('MODEL 1: LOGISTIC REGRESSION')\n",
            "print('=' * 80)\n",
            "\n",
            "# Train Logistic Regression\n",
            "lr_model = LogisticRegression(max_iter=1000, random_state=42, n_jobs=-1)\n",
            "lr_model.fit(X_train, y_train)\n",
            "\n",
            "# Predictions\n",
            "y_train_pred_lr = lr_model.predict(X_train)\n",
            "y_test_pred_lr = lr_model.predict(X_test)\n",
            "y_test_pred_proba_lr = lr_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "# Evaluation\n",
            "train_acc_lr = accuracy_score(y_train, y_train_pred_lr)\n",
            "test_acc_lr = accuracy_score(y_test, y_test_pred_lr)\n",
            "precision_lr = precision_score(y_test, y_test_pred_lr, zero_division=0)\n",
            "recall_lr = recall_score(y_test, y_test_pred_lr, zero_division=0)\n",
            "f1_lr = f1_score(y_test, y_test_pred_lr, zero_division=0)\n",
            "auc_lr = roc_auc_score(y_test, y_test_pred_proba_lr)\n",
            "\n",
            "print(f'\\nTraining Accuracy: {train_acc_lr:.4f}')\n",
            "print(f'Testing Accuracy:  {test_acc_lr:.4f}')\n",
            "print(f'Precision: {precision_lr:.4f}')\n",
            "print(f'Recall:    {recall_lr:.4f}')\n",
            "print(f'F1-Score:  {f1_lr:.4f}')\n",
            "print(f'ROC-AUC:   {auc_lr:.4f}')\n",
            "\n",
            "print(f'\\nConfusion Matrix:')\n",
            "cm_lr = confusion_matrix(y_test, y_test_pred_lr)\n",
            "print(cm_lr)\n",
            "\n",
            "print(f'\\nClassification Report:')\n",
            "print(classification_report(y_test, y_test_pred_lr))\n",
            "\n",
            "# Save model\n",
            "lr_model_path = 'logistic_regression_model.pkl'\n",
            "with open(lr_model_path, 'wb') as f:\n",
            "    pickle.dump(lr_model, f)\n",
            "print(f'\\nModel saved to: {lr_model_path}')"]
    },
    {
        "cell_type": "code",
        "id": "model_2_random_forest",
        "metadata": {},
        "source": [
            "from sklearn.ensemble import RandomForestClassifier\n",
            "\n",
            "print('\\n' + '=' * 80)\n",
            "print('MODEL 2: RANDOM FOREST CLASSIFIER')\n",
            "print('=' * 80)\n",
            "\n",
            "# Train Random Forest\n",
            "rf_model = RandomForestClassifier(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1)\n",
            "rf_model.fit(X_train, y_train)\n",
            "\n",
            "# Predictions\n",
            "y_train_pred_rf = rf_model.predict(X_train)\n",
            "y_test_pred_rf = rf_model.predict(X_test)\n",
            "y_test_pred_proba_rf = rf_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "# Evaluation\n",
            "train_acc_rf = accuracy_score(y_train, y_train_pred_rf)\n",
            "test_acc_rf = accuracy_score(y_test, y_test_pred_rf)\n",
            "precision_rf = precision_score(y_test, y_test_pred_rf, zero_division=0)\n",
            "recall_rf = recall_score(y_test, y_test_pred_rf, zero_division=0)\n",
            "f1_rf = f1_score(y_test, y_test_pred_rf, zero_division=0)\n",
            "auc_rf = roc_auc_score(y_test, y_test_pred_proba_rf)\n",
            "\n",
            "print(f'\\nTraining Accuracy: {train_acc_rf:.4f}')\n",
            "print(f'Testing Accuracy:  {test_acc_rf:.4f}')\n",
            "print(f'Precision: {precision_rf:.4f}')\n",
            "print(f'Recall:    {recall_rf:.4f}')\n",
            "print(f'F1-Score:  {f1_rf:.4f}')\n",
            "print(f'ROC-AUC:   {auc_rf:.4f}')\n",
            "\n",
            "print(f'\\nConfusion Matrix:')\n",
            "cm_rf = confusion_matrix(y_test, y_test_pred_rf)\n",
            "print(cm_rf)\n",
            "\n",
            "print(f'\\nClassification Report:')\n",
            "print(classification_report(y_test, y_test_pred_rf))\n",
            "\n",
            "# Feature importance\n",
            "feature_importance = pd.DataFrame({\n",
            "    'Feature': feature_cols,\n",
            "    'Importance': rf_model.feature_importances_\n",
            "}).sort_values('Importance', ascending=False)\n",
            "\n",
            "print(f'\\nTop 10 Important Features:')\n",
            "print(feature_importance.head(10))\n",
            "\n",
            "# Save model\n",
            "rf_model_path = 'random_forest_model.pkl'\n",
            "with open(rf_model_path, 'wb') as f:\n",
            "    pickle.dump(rf_model, f)\n",
            "print(f'\\nModel saved to: {rf_model_path}')"]
    },
    {
        "cell_type": "code",
        "id": "model_3_gradient_boosting",
        "metadata": {},
        "source": [
            "from sklearn.ensemble import GradientBoostingClassifier\n",
            "\n",
            "print('\\n' + '=' * 80)\n",
            "print('MODEL 3: GRADIENT BOOSTING CLASSIFIER')\n",
            "print('=' * 80)\n",
            "\n",
            "# Train Gradient Boosting\n",
            "gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)\n",
            "gb_model.fit(X_train, y_train)\n",
            "\n",
            "# Predictions\n",
            "y_train_pred_gb = gb_model.predict(X_train)\n",
            "y_test_pred_gb = gb_model.predict(X_test)\n",
            "y_test_pred_proba_gb = gb_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "# Evaluation\n",
            "train_acc_gb = accuracy_score(y_train, y_train_pred_gb)\n",
            "test_acc_gb = accuracy_score(y_test, y_test_pred_gb)\n",
            "precision_gb = precision_score(y_test, y_test_pred_gb, zero_division=0)\n",
            "recall_gb = recall_score(y_test, y_test_pred_gb, zero_division=0)\n",
            "f1_gb = f1_score(y_test, y_test_pred_gb, zero_division=0)\n",
            "auc_gb = roc_auc_score(y_test, y_test_pred_proba_gb)\n",
            "\n",
            "print(f'\\nTraining Accuracy: {train_acc_gb:.4f}')\n",
            "print(f'Testing Accuracy:  {test_acc_gb:.4f}')\n",
            "print(f'Precision: {precision_gb:.4f}')\n",
            "print(f'Recall:    {recall_gb:.4f}')\n",
            "print(f'F1-Score:  {f1_gb:.4f}')\n",
            "print(f'ROC-AUC:   {auc_gb:.4f}')\n",
            "\n",
            "print(f'\\nConfusion Matrix:')\n",
            "cm_gb = confusion_matrix(y_test, y_test_pred_gb)\n",
            "print(cm_gb)\n",
            "\n",
            "print(f'\\nClassification Report:')\n",
            "print(classification_report(y_test, y_test_pred_gb))\n",
            "\n",
            "# Feature importance\n",
            "feature_importance_gb = pd.DataFrame({\n",
            "    'Feature': feature_cols,\n",
            "    'Importance': gb_model.feature_importances_\n",
            "}).sort_values('Importance', ascending=False)\n",
            "\n",
            "print(f'\\nTop 10 Important Features:')\n",
            "print(feature_importance_gb.head(10))\n",
            "\n",
            "# Save model\n",
            "gb_model_path = 'gradient_boosting_model.pkl'\n",
            "with open(gb_model_path, 'wb') as f:\n",
            "    pickle.dump(gb_model, f)\n",
            "print(f'\\nModel saved to: {gb_model_path}')"]
    },
    {
        "cell_type": "code",
        "id": "model_4_svm",
        "metadata": {},
        "source": [
            "from sklearn.svm import SVC\n",
            "\n",
            "print('\\n' + '=' * 80)\n",
            "print('MODEL 4: SUPPORT VECTOR MACHINE (SVM)')\n",
            "print('=' * 80)\n",
            "\n",
            "# Train SVM\n",
            "svm_model = SVC(kernel='rbf', probability=True, random_state=42, gamma='scale')\n",
            "svm_model.fit(X_train, y_train)\n",
            "\n",
            "# Predictions\n",
            "y_train_pred_svm = svm_model.predict(X_train)\n",
            "y_test_pred_svm = svm_model.predict(X_test)\n",
            "y_test_pred_proba_svm = svm_model.predict_proba(X_test)[:, 1]\n",
            "\n",
            "# Evaluation\n",
            "train_acc_svm = accuracy_score(y_train, y_train_pred_svm)\n",
            "test_acc_svm = accuracy_score(y_test, y_test_pred_svm)\n",
            "precision_svm = precision_score(y_test, y_test_pred_svm, zero_division=0)\n",
            "recall_svm = recall_score(y_test, y_test_pred_svm, zero_division=0)\n",
            "f1_svm = f1_score(y_test, y_test_pred_svm, zero_division=0)\n",
            "auc_svm = roc_auc_score(y_test, y_test_pred_proba_svm)\n",
            "\n",
            "print(f'\\nTraining Accuracy: {train_acc_svm:.4f}')\n",
            "print(f'Testing Accuracy:  {test_acc_svm:.4f}')\n",
            "print(f'Precision: {precision_svm:.4f}')\n",
            "print(f'Recall:    {recall_svm:.4f}')\n",
            "print(f'F1-Score:  {f1_svm:.4f}')\n",
            "print(f'ROC-AUC:   {auc_svm:.4f}')\n",
            "\n",
            "print(f'\\nConfusion Matrix:')\n",
            "cm_svm = confusion_matrix(y_test, y_test_pred_svm)\n",
            "print(cm_svm)\n",
            "\n",
            "print(f'\\nClassification Report:')\n",
            "print(classification_report(y_test, y_test_pred_svm))\n",
            "\n",
            "# Save model\n",
            "svm_model_path = 'svm_model.pkl'\n",
            "with open(svm_model_path, 'wb') as f:\n",
            "    pickle.dump(svm_model, f)\n",
            "print(f'\\nModel saved to: {svm_model_path}')"]
    },
    {
        "cell_type": "code",
        "id": "model_5_xgboost",
        "metadata": {},
        "source": [
            "try:\n",
            "    import xgboost as xgb\n",
            "    \n",
            "    print('\\n' + '=' * 80)\n",
            "    print('MODEL 5: XGBOOST CLASSIFIER')\n",
            "    print('=' * 80)\n",
            "    \n",
            "    # Train XGBoost\n",
            "    xgb_model = xgb.XGBClassifier(\n",
            "        n_estimators=100,\n",
            "        learning_rate=0.1,\n",
            "        max_depth=5,\n",
            "        random_state=42,\n",
            "        use_label_encoder=False,\n",
            "        eval_metric='logloss'\n",
            "    )\n",
            "    xgb_model.fit(X_train, y_train)\n",
            "    \n",
            "    # Predictions\n",
            "    y_train_pred_xgb = xgb_model.predict(X_train)\n",
            "    y_test_pred_xgb = xgb_model.predict(X_test)\n",
            "    y_test_pred_proba_xgb = xgb_model.predict_proba(X_test)[:, 1]\n",
            "    \n",
            "    # Evaluation\n",
            "    train_acc_xgb = accuracy_score(y_train, y_train_pred_xgb)\n",
            "    test_acc_xgb = accuracy_score(y_test, y_test_pred_xgb)\n",
            "    precision_xgb = precision_score(y_test, y_test_pred_xgb, zero_division=0)\n",
            "    recall_xgb = recall_score(y_test, y_test_pred_xgb, zero_division=0)\n",
            "    f1_xgb = f1_score(y_test, y_test_pred_xgb, zero_division=0)\n",
            "    auc_xgb = roc_auc_score(y_test, y_test_pred_proba_xgb)\n",
            "    \n",
            "    print(f'\\nTraining Accuracy: {train_acc_xgb:.4f}')\n",
            "    print(f'Testing Accuracy:  {test_acc_xgb:.4f}')\n",
            "    print(f'Precision: {precision_xgb:.4f}')\n",
            "    print(f'Recall:    {recall_xgb:.4f}')\n",
            "    print(f'F1-Score:  {f1_xgb:.4f}')\n",
            "    print(f'ROC-AUC:   {auc_xgb:.4f}')\n",
            "    \n",
            "    print(f'\\nConfusion Matrix:')\n",
            "    cm_xgb = confusion_matrix(y_test, y_test_pred_xgb)\n",
            "    print(cm_xgb)\n",
            "    \n",
            "    print(f'\\nClassification Report:')\n",
            "    print(classification_report(y_test, y_test_pred_xgb))\n",
            "    \n",
            "    # Feature importance\n",
            "    feature_importance_xgb = pd.DataFrame({\n",
            "        'Feature': feature_cols,\n",
            "        'Importance': xgb_model.feature_importances_\n",
            "    }).sort_values('Importance', ascending=False)\n",
            "    \n",
            "    print(f'\\nTop 10 Important Features:')\n",
            "    print(feature_importance_xgb.head(10))\n",
            "    \n",
            "    # Save model\n",
            "    xgb_model_path = 'xgboost_model.pkl'\n",
            "    with open(xgb_model_path, 'wb') as f:\n",
            "        pickle.dump(xgb_model, f)\n",
            "    print(f'\\nModel saved to: {xgb_model_path}')\n",
            "    \n",
            "except ImportError:\n",
            "    print('XGBoost not installed. Skipping this model.')\n",
            "    train_acc_xgb = test_acc_xgb = 0"]
    },
    {
        "cell_type": "markdown",
        "id": "model_comparison",
        "metadata": {},
        "source": ["## M. Model Evaluation & Comparison"]
    },
    {
        "cell_type": "code",
        "id": "compare_models",
        "metadata": {},
        "source": [
            "print('\\n' + '=' * 80)\n",
            "print('MODEL PERFORMANCE COMPARISON')\n",
            "print('=' * 80)\n",
            "\n",
            "# Compile results\n",
            "results = {\n",
            "    'Model': ['Logistic Regression', 'Random Forest', 'Gradient Boosting', 'SVM', 'XGBoost'],\n",
            "    'Train Accuracy': [train_acc_lr, train_acc_rf, train_acc_gb, train_acc_svm, train_acc_xgb],\n",
            "    'Test Accuracy': [test_acc_lr, test_acc_rf, test_acc_gb, test_acc_svm, test_acc_xgb],\n",
            "    'Precision': [precision_lr, precision_rf, precision_gb, precision_svm, precision_xgb],\n",
            "    'Recall': [recall_lr, recall_rf, recall_gb, recall_svm, recall_xgb],\n",
            "    'F1-Score': [f1_lr, f1_rf, f1_gb, f1_svm, f1_xgb],\n",
            "    'ROC-AUC': [auc_lr, auc_rf, auc_gb, auc_svm, auc_xgb]\n",
            "}\n",
            "\n",
            "results_df = pd.DataFrame(results).round(4)\n",
            "print('\\n')\n",
            "print(results_df.to_string(index=False))\n",
            "\n",
            "# Find best model\n",
            "best_idx = results_df['Test Accuracy'].idxmax()\n",
            "best_model_name = results_df.loc[best_idx, 'Model']\n",
            "best_accuracy = results_df.loc[best_idx, 'Test Accuracy']\n",
            "\n",
            "print(f'\\n' + '=' * 80)\n",
            "print(f'BEST MODEL: {best_model_name}')\n",
            "print(f'Test Accuracy: {best_accuracy:.4f} ({best_accuracy*100:.2f}%)')\n",
            "print('=' * 80)\n",
            "\n",
            "if best_accuracy >= 0.90:\n",
            "    print(f'\\nSUCCESS! Model accuracy is >= 90% requirement!')\n",
            "else:\n",
            "    print(f'\\nNote: Model accuracy is {best_accuracy*100:.2f}%, below 90% target.')\n",
            "    print('Consider hyperparameter tuning or ensemble methods.')\n",
            "\n",
            "# Plot accuracy comparison\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "# Accuracy comparison\n",
            "axes[0].barh(results_df['Model'], results_df['Test Accuracy'], color='steelblue')\n",
            "axes[0].axvline(x=0.90, color='red', linestyle='--', label='90% Target')\n",
            "axes[0].set_xlabel('Test Accuracy')\n",
            "axes[0].set_title('Model Test Accuracy Comparison')\n",
            "axes[0].legend()\n",
            "axes[0].set_xlim([0.7, 1.0])\n",
            "axes[0].grid(axis='x', alpha=0.3)\n",
            "\n",
            "# Precision-Recall-F1 comparison\n",
            "x = np.arange(len(results_df))\n",
            "width = 0.25\n",
            "axes[1].bar(x - width, results_df['Precision'], width, label='Precision')\n",
            "axes[1].bar(x, results_df['Recall'], width, label='Recall')\n",
            "axes[1].bar(x + width, results_df['F1-Score'], width, label='F1-Score')\n",
            "axes[1].set_ylabel('Score')\n",
            "axes[1].set_title('Precision, Recall, F1-Score Comparison')\n",
            "axes[1].set_xticks(x)\n",
            "axes[1].set_xticklabels(results_df['Model'], rotation=45, ha='right')\n",
            "axes[1].legend()\n",
            "axes[1].grid(axis='y', alpha=0.3)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# Save results to CSV\n",
            "results_df.to_csv('model_comparison_results.csv', index=False)\n",
            "print('\\nModel comparison results saved to: model_comparison_results.csv')"]
    },
    {
        "cell_type": "code",
        "id": "save_best_model",
        "metadata": {},
        "source": [
            "print('\\n' + '=' * 80)\n",
            "print('SAVING BEST MODEL AND ASSOCIATED OBJECTS')\n",
            "print('=' * 80)\n",
            "\n",
            "# Select best model based on test accuracy\n",
            "models_dict = {\n",
            "    'Logistic Regression': lr_model,\n",
            "    'Random Forest': rf_model,\n",
            "    'Gradient Boosting': gb_model,\n",
            "    'SVM': svm_model,\n",
            "}\n",
            "\n",
            "# Add XGBoost if it was trained (accuracy > 0)\n",
            "if train_acc_xgb > 0:\n",
            "    models_dict['XGBoost'] = xgb_model\n",
            "\n",
            "best_model = models_dict[best_model_name]\n",
            "\n",
            "# Save best model\n",
            "best_model_path = 'best_model.pkl'\n",
            "with open(best_model_path, 'wb') as f:\n",
            "    pickle.dump(best_model, f)\n",
            "print(f'Best model ({best_model_name}) saved to: {best_model_path}')\n",
            "\n",
            "# Save feature names and column order\n",
            "feature_names_path = 'feature_names.pkl'\n",
            "with open(feature_names_path, 'wb') as f:\n",
            "    pickle.dump(feature_cols, f)\n",
            "print(f'Feature names saved to: {feature_names_path}')\n",
            "\n",
            "# Create a comprehensive model info file\n",
            "model_info = {\n",
            "    'best_model_name': best_model_name,\n",
            "    'best_test_accuracy': float(best_accuracy),\n",
            "    'best_train_accuracy': float(results_df.loc[best_idx, 'Train Accuracy']),\n",
            "    'best_precision': float(results_df.loc[best_idx, 'Precision']),\n",
            "    'best_recall': float(results_df.loc[best_idx, 'Recall']),\n",
            "    'best_f1_score': float(results_df.loc[best_idx, 'F1-Score']),\n",
            "    'best_roc_auc': float(results_df.loc[best_idx, 'ROC-AUC']),\n",
            "    'feature_cols': feature_cols,\n",
            "    'scaler_path': 'scaler_weights.pkl',\n",
            "    'model_path': best_model_path,\n",
            "    'feature_names_path': feature_names_path,\n",
            "    'all_models': {\n",
            "        'logistic_regression': 'logistic_regression_model.pkl',\n",
            "        'random_forest': 'random_forest_model.pkl',\n",
            "        'gradient_boosting': 'gradient_boosting_model.pkl',\n",
            "        'svm': 'svm_model.pkl',\n",
            "        'xgboost': 'xgboost_model.pkl' if train_acc_xgb > 0 else None\n",
            "    }\n",
            "}\n",
            "\n",
            "# Save model info as JSON\n",
            "import json\n",
            "model_info_path = 'model_info.json'\n",
            "with open(model_info_path, 'w') as f:\n",
            "    json.dump(model_info, f, indent=2)\n",
            "print(f'Model information saved to: {model_info_path}')\n",
            "\n",
            "print('\\n' + '=' * 80)\n",
            "print('PROJECT COMPLETE!')\n",
            "print('=' * 80)\n",
            "print('\\nFiles created for demo purposes:')\n",
            "print('  1. best_model.pkl - Best trained model')\n",
            "print('  2. scaler_weights.pkl - Feature scaler for preprocessing')\n",
            "print('  3. feature_names.pkl - List of feature column names')\n",
            "print('  4. model_info.json - Model metadata and paths')\n",
            "print('  5. model_comparison_results.csv - All model performance metrics')\n",
            "print('  6. Individual model files for each algorithm')\n",
            "print('\\nTo use the model for predictions:')\n",
            "print('  1. Load the scaler: pickle.load(open(\"scaler_weights.pkl\", \"rb\"))')\n",
            "print('  2. Scale new data: X_new_scaled = scaler.transform(X_new)')\n",
            "print('  3. Load the model: pickle.load(open(\"best_model.pkl\", \"rb\"))')\n",
            "print('  4. Make predictions: predictions = model.predict(X_new_scaled)')"]
    }
]

# Add new cells to notebook
for cell in new_cells:
    nb['cells'].append(cell)

# Write updated notebook
with open('data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print(f"Added {len(new_cells)} cells for model training, evaluation, and saving")
print(f"Total cells now: {len(nb['cells'])}")
