import json

with open('data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# New cells to add
new_cells = [
    {
        "cell_type": "markdown",
        "id": "feature_reduction_intro",
        "metadata": {},
        "source": ["## H. Feature Engineering & Feature Reduction\n",
                   "\n",
                   "### Step 1: Correlation Analysis\n",
                   "Remove highly correlated features to reduce redundancy and improve model efficiency."]
    },
    {
        "cell_type": "code",
        "id": "correlation_analysis",
        "metadata": {},
        "source": [
            "# Correlation Analysis - Remove highly correlated features\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "\n",
            "# Select only numeric columns for correlation (exclude target)\n",
            "numeric_cols = df.select_dtypes(include=[np.number]).columns\n",
            "target_col = 'Purchased'\n",
            "feature_cols = [col for col in numeric_cols if col != target_col]\n",
            "\n",
            "print(f'Features before correlation filtering: {len(feature_cols)}')\n",
            "print(f'Features: {feature_cols}')\n",
            "\n",
            "# Compute correlation matrix\n",
            "corr_matrix = df[feature_cols].corr()\n",
            "\n",
            "# Plot correlation heatmap\n",
            "plt.figure(figsize=(12, 10))\n",
            "sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0,\n",
            "            square=True, linewidths=0.5, cbar_kws={'shrink': 0.8})\n",
            "plt.title('Correlation Matrix of Features', fontsize=14, fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# Find and remove highly correlated features (threshold = 0.95)\n",
            "def find_highly_correlated_pairs(corr_matrix, threshold=0.95):\n",
            "    pairs = []\n",
            "    for i in range(len(corr_matrix.columns)):\n",
            "        for j in range(i+1, len(corr_matrix.columns)):\n",
            "            if abs(corr_matrix.iloc[i, j]) >= threshold:\n",
            "                pairs.append({\n",
            "                    'Feature1': corr_matrix.columns[i],\n",
            "                    'Feature2': corr_matrix.columns[j],\n",
            "                    'Correlation': corr_matrix.iloc[i, j]\n",
            "                })\n",
            "    return pairs\n",
            "\n",
            "highly_correlated = find_highly_correlated_pairs(corr_matrix, threshold=0.95)\n",
            "print(f'Highly correlated feature pairs (|r| >= 0.95):')\n",
            "if highly_correlated:\n",
            "    for pair in highly_correlated:\n",
            "        print(f\"  {pair['Feature1']} <-> {pair['Feature2']}: {pair['Correlation']:.4f}\")\n",
            "else:\n",
            "    print('  No highly correlated pairs found.')\n",
            "\n",
            "# Remove redundant features based on correlation\n",
            "def remove_correlated_features(corr_matrix, threshold=0.95):\n",
            "    cols_to_drop = set()\n",
            "    for i in range(len(corr_matrix.columns)):\n",
            "        for j in range(i+1, len(corr_matrix.columns)):\n",
            "            if abs(corr_matrix.iloc[i, j]) >= threshold:\n",
            "                col_to_drop = corr_matrix.columns[j]\n",
            "                cols_to_drop.add(col_to_drop)\n",
            "    return list(cols_to_drop)\n",
            "\n",
            "cols_to_drop = remove_correlated_features(corr_matrix, threshold=0.95)\n",
            "print(f'Columns to remove due to high correlation: {cols_to_drop}')\n",
            "\n",
            "df_reduced = df.drop(columns=cols_to_drop) if cols_to_drop else df.copy()\n",
            "print(f'Features after correlation filtering: {len(df_reduced.columns) - 1}')\n",
            "print(f'Features retained: {[col for col in df_reduced.columns if col != target_col]}')"]
    },
    {
        "cell_type": "code",
        "id": "pca_analysis",
        "metadata": {},
        "source": [
            "# PCA - Principal Component Analysis for further dimensionality reduction\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "from sklearn.decomposition import PCA\n",
            "\n",
            "print('=== PCA Analysis ===')\n",
            "print('Note: PCA should be applied AFTER scaling, but we will use it here for analysis.')\n",
            "\n",
            "# Get features (non-target columns)\n",
            "feature_cols = [col for col in df_reduced.columns if col != 'Purchased']\n",
            "X = df_reduced[feature_cols].copy()\n",
            "\n",
            "# Check for missing values\n",
            "print(f'Missing values in features:')\n",
            "print(X.isnull().sum())\n",
            "\n",
            "# Standardize for PCA\n",
            "scaler_pca = StandardScaler()\n",
            "X_scaled = scaler_pca.fit_transform(X)\n",
            "\n",
            "# Apply PCA with all components first to see explained variance\n",
            "pca_full = PCA()\n",
            "pca_full.fit(X_scaled)\n",
            "\n",
            "# Calculate cumulative explained variance\n",
            "cumsum_var = np.cumsum(pca_full.explained_variance_ratio_)\n",
            "(n_components,) = np.where(cumsum_var >= 0.95)\n",
            "n_components = n_components[0] + 1 if len(n_components) > 0 else len(feature_cols)\n",
            "\n",
            "print(f'Total features: {len(feature_cols)}')\n",
            "print(f'Components needed for 95 percent variance: {n_components}')\n",
            "print(f'Variance explained by each component (first 10):')\n",
            "for i, var in enumerate(pca_full.explained_variance_ratio_[:min(10, len(feature_cols))], 1):\n",
            "    print(f'  PC{i}: {var:.4f} ({cumsum_var[i-1]:.4f} cumulative)')\n",
            "\n",
            "# Plot explained variance\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "# Individual variance\n",
            "axes[0].bar(range(1, min(11, len(feature_cols)+1)), \n",
            "            pca_full.explained_variance_ratio_[:min(10, len(feature_cols))])\n",
            "axes[0].set_xlabel('Principal Component')\n",
            "axes[0].set_ylabel('Explained Variance Ratio')\n",
            "axes[0].set_title('PCA Explained Variance by Component')\n",
            "axes[0].grid(axis='y', alpha=0.3)\n",
            "\n",
            "# Cumulative variance\n",
            "axes[1].plot(range(1, min(11, len(feature_cols)+1)), \n",
            "             cumsum_var[:min(10, len(feature_cols))], 'bo-')\n",
            "axes[1].axhline(y=0.95, color='r', linestyle='--', label='95 percent threshold')\n",
            "axes[1].set_xlabel('Number of Components')\n",
            "axes[1].set_ylabel('Cumulative Explained Variance')\n",
            "axes[1].set_title('PCA Cumulative Explained Variance')\n",
            "axes[1].legend()\n",
            "axes[1].grid(alpha=0.3)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "print(f'Recommendation: Use {n_components} PCA components to retain 95 percent of variance')\n",
            "print('Note: We will keep original features for interpretability, but can apply PCA if needed.')"]
    },
    {
        "cell_type": "markdown",
        "id": "normality_test_intro",
        "metadata": {},
        "source": ["## I. Normality Testing & Skewness Analysis (Before Scaling)\n",
                   "\n",
                   "Analyze feature distributions and apply log transformation to highly skewed features."]
    },
    {
        "cell_type": "code",
        "id": "skewness_analysis_before",
        "metadata": {},
        "source": [
            "from scipy import stats\n",
            "\n",
            "print('=== Normality Test: Skewness Analysis (BEFORE Scaling) ===')\n",
            "print('\\nSkewness interpretation:')\n",
            "print('  -1 to -0.5: Moderately left-skewed')\n",
            "print('  -0.5 to 0.5: Approximately symmetric')\n",
            "print('  0.5 to 1: Moderately right-skewed')\n",
            "print('  > 1 or < -1: Highly skewed')\n",
            "\n",
            "# Calculate skewness for numeric features\n",
            "feature_cols = [col for col in df_reduced.columns if col != 'Purchased']\n",
            "skewness_data = {}\n",
            "\n",
            "for col in feature_cols:\n",
            "    skew = df_reduced[col].skew()\n",
            "    kurtosis = df_reduced[col].kurtosis()\n",
            "    skewness_data[col] = {'Skewness': skew, 'Kurtosis': kurtosis}\n",
            "\n",
            "# Create DataFrame and display\n",
            "skewness_df = pd.DataFrame(skewness_data).T\n",
            "skewness_df = skewness_df.round(4)\n",
            "print('\\nSkewness and Kurtosis for each feature:')\n",
            "print(skewness_df)\n",
            "\n",
            "# Identify highly skewed features\n",
            "highly_skewed = skewness_df[abs(skewness_df['Skewness']) > 1].index.tolist()\n",
            "print(f'\\nHighly skewed features (|skew| > 1): {highly_skewed}')\n",
            "\n",
            "# Plot distributions before transformation\n",
            "fig, axes = plt.subplots(2, 3, figsize=(15, 10))\n",
            "axes = axes.flatten()\n",
            "\n",
            "for idx, col in enumerate(feature_cols):\n",
            "    if idx < len(axes):\n",
            "        axes[idx].hist(df_reduced[col], bins=30, edgecolor='black', alpha=0.7)\n",
            "        axes[idx].set_title(f'{col} (Skew: {skewness_df.loc[col, \"Skewness\"]:.3f})')\n",
            "        axes[idx].set_xlabel('Value')\n",
            "        axes[idx].set_ylabel('Frequency')\n",
            "        axes[idx].grid(alpha=0.3)\n",
            "\n",
            "# Hide unused subplots\n",
            "for idx in range(len(feature_cols), len(axes)):\n",
            "    axes[idx].set_visible(False)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.suptitle('Feature Distributions BEFORE Scaling', fontsize=14, fontweight='bold', y=1.00)\n",
            "plt.show()"]
    }
]

# Add new cells to notebook
for cell in new_cells:
    nb['cells'].append(cell)

# Write updated notebook
with open('data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print(f"Added {len(new_cells)} cells for correlation analysis and PCA")
print(f"Total cells now: {len(nb['cells'])}")
