import json

# Read the existing notebook
with open('data.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Keep only the first 75 cells (up to outlier handling) and remove the problematic new cells
nb['cells'] = nb['cells'][:75]

# Now add properly structured cells focused on the remaining tasks

model_cells = [
    {
        "cell_type": "markdown",
        "id": "preprocessing_final",
        "metadata": {},
        "source": ["## H-K: Data Preprocessing Pipeline\n",
                   "\n",
                   "Complete preprocessing: feature engineering, reduction, normality testing, and scaling."]
    },
    {
        "cell_type": "code",
        "id": "load_complete_data",
        "metadata": {},
        "source": [
            "# Load the complete dataset with target variable\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "from sklearn.preprocessing import StandardScaler, MinMaxScaler\n",
            "from sklearn.decomposition import PCA\n",
            "from scipy import stats\n",
            "import pickle\n",
            "import warnings\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "# Load the complete dataset\n",
            "df_model = pd.read_csv('social_media_ads_with_target.csv')\n",
            "print('Dataset loaded successfully')\n",
            "print(f'Shape: {df_model.shape}')\n",
            "print(f'Columns: {df_model.columns.tolist()}')\n",
            "print(f'\\nTarget distribution:')\n",
            "print(df_model['Purchased'].value_counts())"]
    },
    {
        "cell_type": "code",
        "id": "feature_preparation",
        "metadata": {},
        "source": [
            "# Prepare features and target\n",
            "print('=== FEATURE PREPARATION ===')\n",
            "\n",
            "# Separate categorical and numeric features\n",
            "categorical_features = df_model.select_dtypes(include=['object']).columns.tolist()\n",
            "numeric_features = df_model.select_dtypes(include=[np.number]).columns.tolist()\n",
            "numeric_features = [col for col in numeric_features if col != 'Purchased']\n",
            "\n",
            "print(f'\\nCategorical features: {categorical_features}')\n",
            "print(f'Numeric features: {numeric_features}')\n",
            "\n",
            "# Encode categorical variables\n",
            "df_encoded = df_model.copy()\n",
            "from sklearn.preprocessing import LabelEncoder\n",
            "\n",
            "label_encoders = {}\n",
            "for col in categorical_features:\n",
            "    le = LabelEncoder()\n",
            "    df_encoded[col] = le.fit_transform(df_encoded[col])\n",
            "    label_encoders[col] = le\n",
            "    print(f'{col}: {dict(zip(le.classes_, le.transform(le.classes_)))}')\n",
            "\n",
            "print(f'\\nDataset shape after encoding: {df_encoded.shape}')\n",
            "print(df_encoded.head())"
        ]
    },
    {
        "cell_type": "code",
        "id": "correlation_analysis_main",
        "metadata": {},
        "source": [
            "print('\\n=== H. CORRELATION ANALYSIS & FEATURE REDUCTION ===')\n",
            "\n",
            "# Calculate correlation matrix for numeric features\n",
            "all_numeric = categorical_features + numeric_features  # All encoded features\n",
            "corr_matrix = df_encoded[all_numeric + numeric_features].corr()\n",
            "\n",
            "# Plot correlation heatmap\n",
            "plt.figure(figsize=(12, 10))\n",
            "sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', center=0,\n",
            "            square=True, linewidths=0.5, cbar_kws={'shrink': 0.8})\n",
            "plt.title('Correlation Matrix of All Features', fontsize=14, fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "# Find highly correlated features (excluding target)\n",
            "feature_list = all_numeric + numeric_features\n",
            "print('\\nHighly correlated feature pairs (|r| >= 0.95):')\n",
            "highly_corr_pairs = []\n",
            "for i in range(len(corr_matrix.columns)):\n",
            "    for j in range(i+1, len(corr_matrix.columns)):\n",
            "        if abs(corr_matrix.iloc[i, j]) >= 0.95:\n",
            "            col1 = corr_matrix.columns[i]\n",
            "            col2 = corr_matrix.columns[j]\n",
            "            corr_val = corr_matrix.iloc[i, j]\n",
            "            print(f'  {col1} <-> {col2}: {corr_val:.4f}')\n",
            "            highly_corr_pairs.append((col1, col2, corr_val))\n",
            "\n",
            "if not highly_corr_pairs:\n",
            "    print('  No highly correlated pairs found.')\n",
            "\n",
            "# Features to keep\n",
            "cols_to_drop = set()\n",
            "for col1, col2, _ in highly_corr_pairs:\n",
            "    cols_to_drop.add(col2)\n",
            "\n",
            "df_reduced = df_encoded.drop(columns=list(cols_to_drop)) if cols_to_drop else df_encoded.copy()\n",
            "print(f'\\nColumns dropped: {list(cols_to_drop)}')\n",
            "print(f'Features after correlation filtering: {len(df_reduced.columns) - 1}')  # -1 for target"
        ]
    },
    {
        "cell_type": "code",
        "id": "pca_analysis_main",
        "metadata": {},
        "source": [
            "print('\\n=== PCA ANALYSIS FOR DIMENSIONALITY REDUCTION ===')\n",
            "\n",
            "# Prepare features for PCA\n",
            "feature_cols_pca = [col for col in df_reduced.columns if col != 'Purchased']\n",
            "X_for_pca = df_reduced[feature_cols_pca].copy()\n",
            "\n",
            "# Standardize for PCA\n",
            "scaler_pca = StandardScaler()\n",
            "X_scaled_pca = scaler_pca.fit_transform(X_for_pca)\n",
            "\n",
            "# Apply PCA\n",
            "pca = PCA()\n",
            "pca.fit(X_scaled_pca)\n",
            "\n",
            "# Analyze variance\n",
            "cumsum_var = np.cumsum(pca.explained_variance_ratio_)\n",
            "n_components_95 = np.argmax(cumsum_var >= 0.95) + 1\n",
            "\n",
            "print(f'\\nTotal features: {len(feature_cols_pca)}')\n",
            "print(f'Components for 95% variance: {n_components_95}')\n",
            "print(f'\\nExplained variance (first 10):')  \n",
            "for i, var in enumerate(pca.explained_variance_ratio_[:10], 1):\n",
            "    print(f'  PC{i}: {var:.4f} ({cumsum_var[i-1]:.4f} cumulative)')\n",
            "\n",
            "# Plot\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "axes[0].bar(range(1, min(11, len(feature_cols_pca)+1)), \n",
            "            pca.explained_variance_ratio_[:10])\n",
            "axes[0].set_title('PCA Explained Variance')\n",
            "axes[0].set_xlabel('Principal Component')\n",
            "axes[0].set_ylabel('Variance Ratio')\n",
            "\n",
            "axes[1].plot(range(1, min(11, len(feature_cols_pca)+1)), \n",
            "             cumsum_var[:10], 'bo-')\n",
            "axes[1].axhline(y=0.95, color='r', linestyle='--', label='95% threshold')\n",
            "axes[1].set_title('Cumulative Explained Variance')\n",
            "axes[1].set_xlabel('Number of Components')\n",
            "axes[1].set_ylabel('Cumulative Variance')\n",
            "axes[1].legend()\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.show()\n",
            "\n",
            "print('\\nNote: Original features retained for interpretability.')"
        ]
    },
    {
        "cell_type": "code",
        "id": "normality_test_before",
        "metadata": {},
        "source": [
            "print('\\n=== I. NORMALITY TEST: SKEWNESS ANALYSIS (BEFORE SCALING) ===')\n",
            "\n",
            "# Select numeric features only for skewness analysis\n",
            "feature_cols = [col for col in df_reduced.columns if col != 'Purchased']\n",
            "numeric_feature_cols = [col for col in feature_cols if df_reduced[col].dtype in [np.int64, np.float64]]\n",
            "\n",
            "skewness_data = {}\n",
            "for col in numeric_feature_cols:\n",
            "    skew = df_reduced[col].skew()\n",
            "    kurt = df_reduced[col].kurtosis()\n",
            "    skewness_data[col] = {'Skewness': skew, 'Kurtosis': kurt}\n",
            "\n",
            "skew_df = pd.DataFrame(skewness_data).T.round(4)\n",
            "print('\\nSkewness and Kurtosis:')\n",
            "print(skew_df)\n",
            "\n",
            "# Identify highly skewed features\n",
            "highly_skewed = [col for col in numeric_feature_cols if abs(df_reduced[col].skew()) > 1]\n",
            "print(f'\\nHighly skewed features (|skew| > 1): {highly_skewed}')\n",
            "\n",
            "# Plot distributions\n",
            "fig, axes = plt.subplots(2, 3, figsize=(15, 10))\n",
            "axes = axes.flatten()\n",
            "\n",
            "for idx, col in enumerate(numeric_feature_cols):\n",
            "    if idx < len(axes):\n",
            "        axes[idx].hist(df_reduced[col], bins=30, edgecolor='black', alpha=0.7)\n",
            "        skew_val = df_reduced[col].skew()\n",
            "        axes[idx].set_title(f'{col} (Skew: {skew_val:.3f})')\n",
            "        axes[idx].set_ylabel('Frequency')\n",
            "        axes[idx].grid(alpha=0.3)\n",
            "\n",
            "for idx in range(len(numeric_feature_cols), len(axes)):\n",
            "    axes[idx].set_visible(False)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.suptitle('Feature Distributions BEFORE Scaling', fontsize=14, fontweight='bold', y=1.00)\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "code",
        "id": "log_transform_features",
        "metadata": {},
        "source": [
            "print('\\n=== LOG TRANSFORMATION FOR HIGHLY SKEWED FEATURES ===')\n",
            "\n",
            "df_transformed = df_reduced.copy()\n",
            "\n",
            "# Apply log1p to highly skewed features\n",
            "for col in highly_skewed:\n",
            "    if (df_transformed[col] >= 0).all():\n",
            "        before_skew = df_transformed[col].skew()\n",
            "        df_transformed[col] = np.log1p(df_transformed[col])\n",
            "        after_skew = df_transformed[col].skew()\n",
            "        print(f'{col}: {before_skew:.4f} -> {after_skew:.4f}')\n",
            "\n",
            "if not highly_skewed:\n",
            "    print('No highly skewed features found.')\n",
            "\n",
            "# Plot transformed distributions\n",
            "fig, axes = plt.subplots(2, 3, figsize=(15, 10))\n",
            "axes = axes.flatten()\n",
            "\n",
            "for idx, col in enumerate(numeric_feature_cols):\n",
            "    if idx < len(axes):\n",
            "        axes[idx].hist(df_transformed[col], bins=30, edgecolor='black', alpha=0.7, color='green')\n",
            "        skew_val = df_transformed[col].skew()\n",
            "        axes[idx].set_title(f'{col} (Skew: {skew_val:.3f})')\n",
            "        axes[idx].set_ylabel('Frequency')\n",
            "        axes[idx].grid(alpha=0.3)\n",
            "\n",
            "for idx in range(len(numeric_feature_cols), len(axes)):\n",
            "    axes[idx].set_visible(False)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.suptitle('Feature Distributions AFTER Log Transformation', fontsize=14, fontweight='bold', y=1.00)\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "code",
        "id": "scaling_normalization_main",
        "metadata": {},
        "source": [
            "print('\\n=== J. SCALING AND NORMALIZATION WITH WEIGHT SAVING ===')\n",
            "\n",
            "# Prepare data for scaling\n",
            "feature_cols_final = [col for col in df_transformed.columns if col != 'Purchased']\n",
            "X = df_transformed[feature_cols_final].copy()\n",
            "y = df_transformed['Purchased'].copy()\n",
            "\n",
            "print(f'\\nFeatures for modeling: {feature_cols_final}')\n",
            "print(f'Feature statistics before scaling:')\n",
            "print(X.describe().round(4))\n",
            "\n",
            "# Initialize and fit MinMaxScaler\n",
            "scaler = MinMaxScaler(feature_range=(0, 1))\n",
            "X_scaled = scaler.fit_transform(X)\n",
            "\n",
            "# Convert to DataFrame\n",
            "X_scaled_df = pd.DataFrame(X_scaled, columns=feature_cols_final)\n",
            "\n",
            "print(f'\\nFeature statistics after MinMaxScaler (0-1 range):')\n",
            "print(X_scaled_df.describe().round(4))\n",
            "\n",
            "# Save scaler\n",
            "with open('scaler_weights.pkl', 'wb') as f:\n",
            "    pickle.dump(scaler, f)\n",
            "print(f'\\nScaler saved to: scaler_weights.pkl')\n",
            "print(f'Min: {scaler.data_min_}')\n",
            "print(f'Max: {scaler.data_max_}')"
        ]
    },
    {
        "cell_type": "code",
        "id": "normality_test_after",
        "metadata": {},
        "source": [
            "print('\\n=== K. NORMALITY TEST: SKEWNESS ANALYSIS (AFTER SCALING) ===')\n",
            "\n",
            "skew_after = {}\n",
            "for col in numeric_feature_cols:\n",
            "    skew_after[col] = X_scaled_df[col].skew()\n",
            "\n",
            "print('\\nSkewness after scaling (MinMaxScaler preserves skewness):')\n",
            "for col in numeric_feature_cols:\n",
            "    skew_before = skewness_data[col]['Skewness']\n",
            "    skew_now = skew_after[col]\n",
            "    print(f'{col:20} Before: {skew_before:8.4f}  After: {skew_now:8.4f}')"
        ]
    }
]

# Add model cells
for cell in model_cells:
    cell['execution_count'] = None
    cell['outputs'] = [] if cell['cell_type'] == 'code' else None
    nb['cells'].append(cell)

# Write updated notebook
with open('data.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Reset and added preprocessing cells")
print(f"Total cells: {len(nb['cells'])}")
